server:
  port: 8083

spring:
  application:
    name: weixin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/keycloak2?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root

  # redis 配置
  data:
    redis:
      database: 0
      host: 172.16.0.130
      password: wap
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池的最大数据库连接数
          max-active: 200
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.weixin.request.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.weixin.request.dao: info
  file:
    path: /root/yanglao
